name: Update VPN Config
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run filter
        run: |
          # Скачиваем базу
          curl -L "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-CIDR-RU-all.txt" > all.txt
          
          # 2. Удаляем только два элемента: Russia и Anycast
          # Больше ничего не фильтруем
          grep -vEi "Russia|Anycast" all.txt > my.txt
          
          # Считаем, сколько осталось для проверки
          COUNT=$(wc -l < my.txt)
          sed -i "1i # Количество после чистки: $COUNT" my.txt
          
          # Пакуем в JSON для Gist
          jq -Rs '{files: {"auto.txt": {content: .}}}' my.txt > p.json
          
          # Отправляем в твой Gist
          curl -X PATCH -H "Authorization: token ${{ secrets.GIST_TOKEN }}" -H "Content-Type: application/json" -d @p.json https://api.github.com/gists/633322f43c3751c0c8bc983d8f6f12e0
          - name: Run Black Filter
          run: |
          # 1. Скачиваем базу от Нового автора
          curl -L "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/BLACK_SS+All_RUS.txt" > black_all.txt

          # 2. Удаляем Россию и Anycast
          grep -vEi "Russia|Anycast" black_all.txt > black_my.txt

          # 3. Считаем итог и добавляем заголовок
          COUNT=$(wc -l < black_my.txt)
          sed -i "1i # Чистые конфиги (без RU/Anycast): $COUNT" black_my.txt

          # 4. Пакуем для твоего нового Gist (файл black.txt)
          jq -Rs '{files: {"black.txt": {content: .}}}' black_my.txt > black.json

          # 5. Отправляєм в Gist через созданный нами секрет
          curl -X PATCH -H "Authorization: token ${{ secrets.GIST_TOKEN }}" -H "Content-Type: application/json" -d @black.json https://api.github.com/gists/${{ secrets.GIST_ID_BLACK }}
