name: Update VPN Config
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run filter
        run: |
          # --- ГРУППА 1: Собираем 4 подписки в auto.txt ---
          # 1. Первая ссылка (создаем файл)
          curl -L "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-CIDR-RU-all.txt" > all.txt
          
          # 2. Добавляем еще 3 подписки в этот же файл (через >>)
          curl -L "https://raw.githubusercontent.com/zieng2/wl/main/vless_universal.txt" >> all.txt
          curl -L "https://codeberg.org/zieng2/wl/raw/branch/main/vless_universal.txt" >> all.txt
          curl -L "https://gitlab.com/zieng2/wl/raw/main/vless_universal.txt" >> all.txt

          # 3. Чистим всю кучу от Russia и Anycast (фильтр только по названиям)
          grep -vE "#.*(Russia|Anycast)" all.txt > my.txt
          
          # 4. Считаем итог и отправляем в Gist (файл auto.txt)
          COUNT=$(wc -l < my.txt)
          sed -i "1i # Обновлено: $(date) | Собрано из 4 подписок: $COUNT" my.txt
          jq -Rs '{files: {"auto.txt": {content: .}}}' my.txt > p.json
          curl -X PATCH -H "Authorization: token ${{ secrets.GIST_TOKEN }}" -H "Content-Type: application/json" -d @p.json https://api.github.com/gists/633322f43c3751c0c8bc983df6f12e0

          # --- ГРУППА 2: Пятая подписка в black.txt ---
          # 1. Скачиваем отдельную базу
          curl -L "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/BLACK_SS+All_RUS.txt" > black_all.txt
          
          # 2. Чистим её
          grep -vE "#.*(Russia|Anycast)" black_all.txt > black_my.txt
          
          # 3. Считаем итог и отправляем в Gist (файл black.txt)
          COUNT_B=$(wc -l < black_my.txt)
          sed -i "1i # Обновлено: $(date) | Из пятой подписки: $COUNT_B" black_my.txt
          jq -Rs '{files: {"black.txt": {content: .}}}' black_my.txt > black.json
          curl -X PATCH -H "Authorization: token ${{ secrets.GIST_TOKEN }}" -H "Content-Type: application/json" -d @black.json https://api.github.com/gists/633322f43c3751c0c8bc983df6f12e0
