name: Update VPN Config
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run filter
        run: |
          # --- ШАГ 1: Обновляем auto.txt (Ювелирный фильтр) ---
          curl -L "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-CIDR-RU-all.txt" > all.txt
          curl -L "https://raw.githubusercontent.com/zieng2/wl/main/vless_universal.txt" >> all.txt
          curl -L "https://codeberg.org/zieng2/wl/raw/branch/main/vless_universal.txt" >> all.txt
          curl -L "https://gitlab.com/zieng2/wl/raw/main/vless_universal.txt" >> all.txt

          # Ювелирная чистка: удаляем только конкретные технические адреса Сбера, не трогая ключи
          grep -vE "(-def\.sbrf-cdn342\.ru)" all.txt > step1.txt || true

          # Чистка по флагам и названиям хостингов в самом конце строки (после #)
          grep -vE "#.*\s?([🇷🇺RUРФ]|Russia|Anycast|Yandex|CDNvideo|cloud\.ru|Delta|e-Style|Selectel|Timeweb|UFO Hosting|UFOHosting|Beget|EuroByte|Sprinthost|THE\.Hosting)" step1.txt > my.txt || true
          
          COUNT_A=$(wc -l < my.txt)
          sed -i "1i # Обновлено: $(date) | Конфигов: $COUNT_A" my.txt
          
          jq -Rs '{files: {"auto.txt": {content: .}}}' my.txt > p_auto.json
          curl -X PATCH -H "Authorization: token ${{ secrets.GIST_TOKEN }}" -H "Content-Type: application/json" -d @p_auto.json https://api.github.com/gists/633322f43c3751c0c8bc983d8f6f12e0

          # --- ШАГ 2: Обновляем black.txt ---
          curl -L "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/BLACK_SS+All_RUS.txt" > black_all.txt
          
          grep -vE "#.*(Russia|Anycast)" black_all.txt > black_my.txt
          
          COUNT_B=$(wc -l < black_my.txt)
          sed -i "1i # Обновлено: $(date) | Конфигов: $COUNT_B" black_my.txt
          jq -Rs '{files: {"black.txt": {content: .}}}' black_my.txt > p_black.json
          curl -X PATCH -H "Authorization: token ${{ secrets.GIST_TOKEN }}" -H "Content-Type: application/json" -d @p_black.json https://api.github.com/gists/3bc9b1c65c9036c02003fa6cfb7c1247
